@TaskManager.Api_HostAddress = http://localhost:5165

GET {{TaskManager.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TaskManager.Api_HostAddress}}/api/tasks
Content-Type: application/json

{
  "title": "Testar validação da TaskItem",
  "description": "Confirmar que tarefas válidas continuam funcionando",
  "dueDate": "2026-08-25T18:00:00"
}

###

GET {{TaskManager.Api_HostAddress}}/api/tasks
Accept: application/json

###

GET {{TaskManager.Api_HostAddress}}/api/tasks/00000000-0000-0000-0000-000000000000
Accept: application/json

###

PUT {{TaskManager.Api_HostAddress}}/api/tasks/8d3e3c84-420f-4f1a-95cd-ff9702022205
Content-Type: application/json
{
  "title": "Tarefa atualizada pelo PUT",
  "description": "Testando o fluxo de atualização",
  "dueDate": "2026-09-01T18:00:00"
}

###

PUT {{TaskManager.Api_HostAddress}}/api/tasks/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "title": "Tarefa inexistente",
  "description": "Este registro não existe",
  "dueDate": "2026-09-01T18:00:00"
}

###

PUT {{TaskManager.Api_HostAddress}}/api/tasks/8d3e3c84-420f-4f1a-95cd-ff9702022205
Content-Type: application/json

{
  "title": "",
  "description": "Tentando inserir título inválido",
  "dueDate": "2026-09-01T18:00:00"
}

###

DELETE {{TaskManager.Api_HostAddress}}/api/tasks/be208efd-96fe-4753-b8b7-f8683d2aa366
Accept: application/json

###
GET {{TaskManager.Api_HostAddress}}/api/tasks/be208efd-96fe-4753-b8b7-f8683d2aa366
Accept: application/json

###

POST {{TaskManager.Api_HostAddress}}/api/tasks
Content-Type: application/json
{
  "title": "Testar start da TaskItem",
  "description": "Confirmar que tarefa muda para InProgress",
  "dueDate": "2026-08-25T18:00:00"
}

###

POST {{TaskManager.Api_HostAddress}}/api/tasks/8c3fd483-80ec-4f8e-8961-7e9edf2578f0/start
Accept: application/json

###
POST {{TaskManager.Api_HostAddress}}/api/tasks/8c3fd483-80ec-4f8e-8961-7e9edf2578f0/complete
Accept: application/json

###
POST {{TaskManager.Api_HostAddress}}/api/tasks/00000000-0000-0000-0000-000000000000/start
Accept: application/json

###
POST {{TaskManager.Api_HostAddress}}/api/tasks/00000000-0000-0000-0000-000000000000/complete
Accept: application/json